events {
  worker_connections 1024;
}

http {
  upstream account-service  { server account-service:3001; }
  upstream transaction-service { server transaction-service:3002; }
  upstream ledger-service    { server ledger-service:3003; }
  upstream fx-service        { server fx-service:3004; }
  upstream payroll-service   { server payroll-service:3005; }
  upstream admin-service     { server admin-service:3006; }

  server {
    listen 80;

    location /api/accounts {
      proxy_pass http://account-service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/transfers {
      proxy_pass http://transaction-service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ledger {
      proxy_pass http://ledger-service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/fx {
      proxy_pass http://fx-service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/payroll {
      proxy_pass http://payroll-service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/admin {
      proxy_pass http://admin-service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
